---
# MegaLinter GitHub Action configuration file
# https://megalinter.github.io

name: MegaLinter
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: "${{ github.ref }}-${{ github.workflow }}"
  cancel-in-progress: true
jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: "${{ secrets.PAT || secrets.GITHUB_TOKEN }}"
          fetch-depth: 0
      - name: MegaLinter
        id: ml
        uses: megalinter/megalinter/flavors/java@v5 ## latest release of major version
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" # report individual linter status
          # Validate all source when push on main, else just the git diff with live.
          VALIDATE_ALL_CODEBASE: >-
            ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}

          PARALLEL: true

          # Specific linters to run
          ENABLE: CREDENTIALS,MARKDOWN,GIT,SPELL,YAML
          SPELL_CSPELL_DISABLE_ERRORS: true
          SPELL_MISSPELL_DISABLE_ERRORS: true
          MARKDOWN_MARKDOWNLINT_DISABLE_ERRORS: true
          MARKDOWN_MARKDOWNLINT_CONFIG_FILE: ".github/linters/markdown-lint.yaml"
          MARKDOWN_MARKDOWN_LINK_CHECK_CONFIG_FILE: ".github/linters/markdown-lint-check.json"
          MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
          # MARKDOWN_MARKDOWN_LINK_CHECK_CLI_LINT_MODE: "project"
          MARKDOWN_REMARK_LINT_DISABLE_ERRORS: true
          # MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
          # MARKDOWN_MARKDOWN_TABLE_FORMATTER_DISABLE_ERRORS: true
          #  - CLOJURE
          # CLOJURE_CLJ_KONDO_ARGUMENTS: '--lint deps.edn'

          # ADD CUSTOM ENV VARIABLES OR DEFINE IN A FILE .mega-linter.yml AT ROOT OF REPOSITORY
          # DISABLE: COPYPASTE,SPELL # Uncomment to disable copy-paste and spell checks
