---
name: Publish Book
on:
  # Manually trigger workflow
  workflow_dispatch:

  # Run work flow conditional on linter workflow success
  workflow_run:
    workflows:
      - "MegaLinter"
    paths:
      - "docs/**"
      - "includes/**"
      - "overrides/**"
      - "mkdocs.yaml"
    branches:
      - main
    types:
      - completed

permissions:
  contents: write

jobs:
  publish-book:
    name: MkDocs Publish
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸš€ Job automatically triggered by ${{ github.event_name }}"
      - run: echo "ğŸ§ Job running on ${{ runner.os }} server"
      - run: echo "ğŸ™ Using ${{ github.ref }} branch from ${{ github.repository }} repository"

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            docs
            includes
            overrides
      - run: echo "ğŸ™ ${{ github.repository }} repository sparse-checkout to the CI runner."

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Cache
        uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache

      - run: pip install mkdocs-material mkdocs-callouts mkdocs-glightbox mkdocs-git-revision-date-localized-plugin mkdocs-redirects pillow cairosvg
      - run: mkdocs gh-deploy --force
      - run: echo "ğŸ™ ."

      # Summary and status
      - run: echo "ğŸ¨ MkDocs Publish Book workflow completed"
      - run: echo "ğŸ Job status is ${{ job.status }}."
